// src/pages/Blog.tsx
import { useMemo, useState } from 'react';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { BlogPostCard } from '../components/BlogPostCard';
import postsJson from '../data/posts.json';
import type { Post } from '../types/post';

const ALL: Post[] = postsJson as Post[];

export function Blog() {
  const itemsPerPage = 6;

  const { destaque, pool } = useMemo(() => {
    const featured = ALL.find((p) => p.destaque) ?? ALL[0];
    const rest = ALL.filter((p) => p.id !== featured.id);
    return { destaque: featured, pool: rest };
  }, []);

  const [visibleCount, setVisibleCount] = useState(itemsPerPage);
  const posts = pool.slice(0, visibleCount);
  const canLoadMore = visibleCount < pool.length;

  function loadMore() {
    setVisibleCount((c) => Math.min(c + itemsPerPage, pool.length));
  }

  return (
    <>
      <Header />
      <section className="container mt-8 mx-auto w-10/12">
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-3 md:col-span-1">
            <h1 className="font-zerocalcare text-6xl text-orange mb-20">FIQUE POR DENTRO</h1>
          </div>
          <div className="col-span-3 md:col-span-2">
            {destaque && <BlogPostCard post={destaque} destaque />}
          </div>
        </div>
      </section>
      <section className="container relative text-center mx-auto w-10/12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {posts.map((item) => (
            <BlogPostCard key={item.id} post={item} />
          ))}
        </div>
        {canLoadMore && (
          <button
            type="button"
            className="mt-8 font-museoRegular rounded-button bg-orange text-md h-12 px-8 uppercase border-2 border-solid border-orange text-center hover:bg-white hover:text-orange focus:outline-none"
            onClick={loadMore}
          >
            Carregar mais
          </button>
        )}
      </section>
      <Footer />
    </>
  );
}

// legacy/src/app/pages/annonymous/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { PostModel } from 'src/app/models/post.model';
import { PostService } from 'src/app/services/posts.service';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.scss']
})
export class BlogComponent implements OnInit {

  posts: PostModel[] = [];
  postDestaque: PostModel = undefined;
  itemsPerPage = 6;
  offset = 0;
  constructor(private postService: PostService) { }

  ngOnInit(): void {
    this.loadItens();
    this.postService.getList(1, 0, true).subscribe((result: PostModel[]) => this.postDestaque = result[0]);
  }

  loadMore(): void {
    this.offset += this.itemsPerPage;
    this.loadItens();
  }

  loadItens(): void {
    this.postService.getList(this.itemsPerPage, this.offset, false).subscribe((result: PostModel[]) => this.posts = this.posts.concat(result));
  }
}


<app-header></app-header>
<section class="container mt-8 mx-auto w-10/12">
  <div class="grid grid-cols-3 gap-4">
    <div class="col-span-3 md:col-span-1">
      <h1 class="font-zerocalcare text-6xl text-orange mb-20">FIQUE POR DENTRO</h1>
    </div>
    <div class="col-span-3 md:col-span-2" *ngIf="postDestaque">
      <app-blog-post [post]="postDestaque" [destaque]="true"></app-blog-post>
    </div>
  </div>
</section>
<section class="container relative text-center mx-auto w-10/12">
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-4" infiniteScroll (scrolled)="loadMore()">
    <app-blog-post *ngFor="let item of posts" [post]="item"></app-blog-post>
  </div>
</section>
<app-footer></app-footer>
